name: CICD for Car Price Prediction A3

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to project repository
      uses: actions/checkout@v3


    - name: Python environment setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'


    - name: Install dependencies for project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Execute unit tests
      run: |
        pytest
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Project Repo
      uses: actions/checkout@v3

    - name: DockerHub Authentication
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Create Docker Deployment Image
      run: docker build -t inisha5563/car_price_prediction:a3 .

    - name: Deploy Docker Image to DockerHub
      run: docker push inisha5563/car_price_prediction:a3

  deploy:
    # environment: Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ vars.PROXY_HOST }}
          proxy_username: ${{ secrets.USERNAME }}
          proxy_password: ${{ secrets.PROXY_PASSWORD }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull inisha5563/a3-car-price:latest
            docker compose -f st125563/docker-compose.yaml down --remove-orphans
            docker compose -f st125563/docker-compose.yaml down --remove-orphans 
            docker compose -f st125563/docker-compose.yaml up -d